catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: url
      target: https://raw.githubusercontent.com/raphaelmorsch/rhdh-canal-digital-template/main/template.yaml
