apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  description: Aplicação Quarkus onboardada via Golden Template para OpenShift.
  annotations:
    backstage.io/kubernetes-id: ${{ values.componentId }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/source-location: url:${{ values.sourceRepoUrl }}
    janus-idp.io/tekton: ${{ values.componentId }}
    argocd/app-name: ${{ values.componentId }}
  tags:
    - quarkus
    - java17
    - openshift
    - serverless
  links:
    - url: https://devspaces.apps.cluster-4bll2.dynamic2.redhatworkshops.io/#https://github.com/raphaelmorsch/canal-digital-quarkus.git
      title: Open in Dev Spaces
      icon: web
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner }}
  system: canal-digital
