apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  description: Aplicação Quarkus onboardada via Golden Template para OpenShift.
  annotations:
    backstage.io/source-location: url:${{ values.sourceRepoUrl }}
    janus-idp.io/tekton: ${{ values.componentId }}
    argocd/app-name: ${{ values.componentId }}
  tags:
    - quarkus
    - java17
    - openshift
    - serverless
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner }}
  system: canal-digital
