apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ${{ values.componentId }}
  labels:
    backstage.io/kubernetes-id: ${{ values.componentId }}
    app.kubernetes.io/name: ${{ values.componentId }}
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/runtime-version: openjdk-17-ubi8
    pipeline.openshift.io/type: kubernetes
spec:
  params:
    - name: APP_NAME
      type: string
      default: ${{ values.componentId }}
    - name: GIT_REPO
      type: string
      default: ${{ values.sourceRepoUrl }}
    - name: GIT_REVISION
      type: string
      default: ${{ values.sourceBranch }}
    - name: IMAGE_NAME
      type: string
      default: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.imageStreamName }}:latest
    - name: PATH_CONTEXT
      type: string
      default: .
    - name: VERSION
      type: string
      default: openjdk-17-ubi8
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: SUBDIRECTORY
          value: ""
        - name: DELETE_EXISTING
          value: "true"
      workspaces:
        - name: output
          workspace: workspace

    - name: build
      runAfter:
        - fetch-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-java
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLS_VERIFY
          value: "false"
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      workspaces:
        - name: source
          workspace: workspace